"""uses enum

Revision ID: 15d459b77fd1
Revises: aaf0dc9afa86
Create Date: 2025-07-22 19:43:39.786245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d459b77fd1'
down_revision = 'aaf0dc9afa86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches_table', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Regular Season', 'Exhibition', 'Elimination', 'Quarterfinal', 'Semifinal', 'Final', 'Third place', 'Practice', name='match_category'),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Unscheduled', 'Scheduled', 'In Progress', 'Completed', 'Cancelled', 'Postponed', name='match_status'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches_table', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Unscheduled', 'Scheduled', 'In Progress', 'Completed', 'Cancelled', 'Postponed', name='match_status'),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.Enum('Regular Season', 'Exhibition', 'Elimination', 'Quarterfinal', 'Semifinal', 'Final', 'Third place', 'Practice', name='match_category'),
               type_=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
