"""added sponsors to the league resource

Revision ID: 4675eb2c9135
Revises: f2739c19aa00
Create Date: 2025-07-08 15:10:12.256175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4675eb2c9135'
down_revision = 'f2739c19aa00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_resource_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_sponsors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('leagues_table', schema=None) as batch_op:
        batch_op.drop_column('sponsors')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsors', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('league_resource_table', schema=None) as batch_op:
        batch_op.drop_column('league_sponsors')

    # ### end Alembic commands ###
