"""add staging

Revision ID: 49b1d830f281
Revises: dfeaef489a54
Create Date: 2025-07-27 17:06:34.081807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b1d830f281'
down_revision = 'dfeaef489a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'match_stages', ['stage_id'], ['stage_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('stage_id')

    # ### end Alembic commands ###
