"""added payment

Revision ID: 571e52726acb
Revises: 4675eb2c9135
Create Date: 2025-07-13 21:35:42.558915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571e52726acb'
down_revision = '4675eb2c9135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_teams_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.Enum('Pending', 'Paid Online', 'Paid On Site', 'Waived', name='league_team_payment_status'), nullable=False))
        batch_op.alter_column('league_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint('league_teams_table_league_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'leagues_table', ['league_id'], ['league_id'], ondelete='CASCADE')

    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.drop_constraint('teams_table_active_league_id_fkey', type_='foreignkey')
        batch_op.drop_column('active_league_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_league_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('teams_table_active_league_id_fkey', 'leagues_table', ['active_league_id'], ['league_id'])

    with op.batch_alter_table('league_teams_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('league_teams_table_league_id_fkey', 'leagues_table', ['league_id'], ['league_id'])
        batch_op.alter_column('league_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('payment_status')
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###
