"""added intrance free for category

Revision ID: 799e4d23eaef
Revises: 829079784b39
Create Date: 2025-06-27 21:53:37.311431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799e4d23eaef'
down_revision = '829079784b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_categories_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrance_fee_amount', sa.Float(), nullable=True))

    with op.batch_alter_table('leagues_table', schema=None) as batch_op:
        batch_op.drop_column('entrance_fee_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrance_fee_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('league_categories_table', schema=None) as batch_op:
        batch_op.drop_column('entrance_fee_amount')

    # ### end Alembic commands ###
