"""added format type

Revision ID: 7bdf8dd21103
Revises: 49b1d830f281
Create Date: 2025-07-27 17:57:08.120450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7bdf8dd21103'
down_revision = '49b1d830f281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_stages')
    with op.batch_alter_table('matches_table', schema=None) as batch_op:
        batch_op.drop_constraint('matches_table_stage_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'match_stages_table', ['stage_id'], ['stage_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('matches_table_stage_id_fkey', 'match_stages', ['stage_id'], ['stage_id'], ondelete='CASCADE')

    op.create_table('match_stages',
    sa.Column('stage_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('league_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('division_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pairing_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('top_n_teams', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('auto_generate', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('match_options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('vs_teams_generated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('stage_id', name='match_stages_pkey')
    )
    # ### end Alembic commands ###
