"""added is accepted

Revision ID: 829079784b39
Revises: 2ab31563af01
Create Date: 2025-06-25 11:33:39.262568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829079784b39'
down_revision = '2ab31563af01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_team_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accepted', sa.Enum('Pending', 'Accepted', 'Rejected', name='player_is_accepted'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_team_table', schema=None) as batch_op:
        batch_op.drop_column('is_accepted')

    # ### end Alembic commands ###
