"""remove audit log

Revision ID: 8747fbf9d377
Revises: eb2db96bdf10
Create Date: 2025-07-17 06:41:37.713832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8747fbf9d377'
down_revision = 'eb2db96bdf10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('audit_by_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('audit_by_type', postgresql.ENUM('Player', 'Team_Creator', 'League_Administrator_Local', 'League_Administrator_LGU', 'System', name='account_type_enum'), autoincrement=False, nullable=False),
    sa.Column('audit_to_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('audit_to_type', postgresql.ENUM('Player', 'Team_Creator', 'League_Administrator_Local', 'League_Administrator_LGU', 'System', name='account_type_enum'), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('audit_id', name='audit_logs_pkey')
    )
    # ### end Alembic commands ###
