"""remove relation with player as team captain in team

Revision ID: a04a1f3a2193
Revises: 8747fbf9d377
Create Date: 2025-07-17 06:55:50.654494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04a1f3a2193'
down_revision = '8747fbf9d377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_team_captain_id', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_team_captain_id', 'player_team_table', ['team_captain_id'], ['player_team_id'], deferrable=True)

    # ### end Alembic commands ###
