"""changes on tropies

Revision ID: b7545e8c0c0c
Revises: 799e4d23eaef
Create Date: 2025-06-29 19:40:58.941486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7545e8c0c0c'
down_revision = '799e4d23eaef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues_table', schema=None) as batch_op:
        batch_op.drop_column('championship_trophy_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('championship_trophy_url', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
