"""remove description length

Revision ID: e3731add0375
Revises: b7545e8c0c0c
Create Date: 2025-06-29 23:15:50.679710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3731add0375'
down_revision = 'b7545e8c0c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues_table', schema=None) as batch_op:
        batch_op.alter_column('league_description',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues_table', schema=None) as batch_op:
        batch_op.alter_column('league_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
