"""removed contact in league admin

Revision ID: eb2db96bdf10
Revises: 571e52726acb
Create Date: 2025-07-17 06:34:38.794491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2db96bdf10'
down_revision = '571e52726acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_administrator_table', schema=None) as batch_op:
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_administrator_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
