"""remove docs

Revision ID: f2739c19aa00
Revises: 181825ea455d
Create Date: 2025-07-01 21:36:34.965068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2739c19aa00'
down_revision = '181825ea455d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players_table', schema=None) as batch_op:
        batch_op.drop_column('document_url_2')
        batch_op.drop_column('document_url_1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_url_1', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('document_url_2', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
